// <auto-generated />
namespace ClothesLine_Sm_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tr1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tr1));
        
        string IMigrationMetadata.Id
        {
            get { return "201903122241457_tr1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
